### ISSUE TITLE
Lodash GroupBy is x15 faster

### ISSUE THREAD

**Issue by Nisgrak** [meyfa/group-items#95]
Hi! 

I always search for a replace to `lodash.groupby` lib because of his TS types, I found your lib but is too much slow in a benchmark.

I use in a real project to group an array of 1kk records and is crazy how long it takes (much much more than in the benchmark)

I make a minimal bench so you can test
https://stackblitz.com/edit/node-bv3gtc?file=bench.ts
Execute `npm i && tsx bench.ts` and check if you can see a improvement!

![image](https://user-images.githubusercontent.com/19597708/198337420-13eae3c1-06f4-4619-8287-6cfe0c806e76.png)

Anyway, thanks for your work and you lib!

**Comment by meyfa** [comment]
Thanks for the feedback! I didn't have performance in mind when creating this library since my dataset was very small. There are probably many opportunities for optimization. Perhaps somebody wants to find out what the bottleneck is? I'm somewhat time-constrained unfortunately, so I can't tell when I will get around to that. And if you (or anyone else) sees optimization opportunities, I'd be happy to accept a PR!

**Comment by meyfa** [comment]
@Nisgrak I updated group-items to v2.2.1 in the benchmark you shared, and it now outperforms Lodash in the first case and is almost equally as fast in the second case:

![image](https://user-images.githubusercontent.com/3982806/228522622-fab0fe98-260d-4bc6-abe7-6b35285243bd.png)
